version: 1.0

models:
  - name: Product categories
    source: product.category
    target : product.category
    fields:
      - name
      - parent_id
      - property_account_income_categ_id
      - property_account_expense_categ_id
    # filter: 
    #   - []