version: 1.0

models:
  - name: Products template
    source: product.template
    target : product.template
    fields:
      - name
      - categ_id
      - type>detailed_type
      - default_code
      - recurring_invoice
      - sale_ok
      - sale_delay
      - purchase_ok
      - purchase_method
      - invoice_policy
      - description
      - description_sale
      - currency_id
      - must_have_dates
      - standard_price
      - list_price
      # - responsible_id
      - uom_id
      - uom_po_id
      - sale_line_warn
      - sale_line_warn_msg
      - purchase_line_warn
      - purchase_line_warn_msg
    filter: 
      - ['id', '>', 771 ]
    xmlid_mappings:
      __export__.product_uom_4: uom.product_uom_hour
      __export__.product_uom_3: uom.product_uom_day
      __export__.product_uom_20: mwprog_sale_subscription_mutation.product_uom_year
      __export__.product_uom_6: uom.product_uom_meter
      __export__.product_uom_5: uom.product_uom_km
      __export__.product_uom_7: mwprog_sale_subscription_mutation.product_uom_month


