version: 1.0

models:
  - name: Products product
    source: product.product
    target : product.product
    fields:
      - name
      - categ_id
      - type>detailed_type
      - default_code
      - recurring_invoice
      - sale_ok
      - purchase_ok
      - invoice_policy
      - description
      - description_sale
      - currency_id
      - must_have_dates
      - standard_price
      - list_price
      # - responsible_id
    filter: 
      - ['id', '>', 1512 ]
    # # # limit: 10