version: 1.0

models:
  - name: Products template
    source: product.template
    target : product.template
    fields:
      - name
      - categ_id
      - type>detailed_type
      - default_code
      - recurring_invoice
      - sale_ok
      - purchase_ok
      - invoice_policy
      - description
      - description_sale
      - currency_id
      - must_have_dates
      - standard_price
      - list_price      
    # filter: 
    #   - ['id', '=', 84 ]
    # # limit: 10